version: '2'
services:
  mariaDBFullStack:
    image: arm64v8/mariadb
    hostname: mariadbFullStack
    container_name: mariaDBFullStack
    restart: always
    volumes:
      - /Users/patjawat/Downloads/:/home/
      - ./docker/mariadb/data/:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=% 
  # mongo:
  #   image: mongo:4.4
  #   ports:
  #       - 27017:27017
  #   environment:
  #         - MONGO_INITDB_ROOT_USERNAME=root
  #         - MONGO_INITDB_ROOT_PASSWORD=docker
  #         - MONGO_INITDB_DATABASE=admin
  #         - MONGO_INITDB_USERNAME=admin
  #         - MONGO_INITDB_PASSWORD=112233
  #   volumes:
  #         - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  #         - ./docker/mongo:/data/db

  phpmyadmin_fullstack:
    image: arm64v8/phpmyadmin
    restart: always
    links:
      - mariaDBFullStack:db
    ports:
      - 8200:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mariaDBFullStack